export interface DDDInfo {
  city: string;
  state: string;
}

export const dddMap: Record<string, DDDInfo> = {
  "11": { city: "Sao Paulo", state: "SP" },
  "12": { city: "Sao Jose dos Campos", state: "SP" },
  "13": { city: "Santos", state: "SP" },
  "14": { city: "Bauru", state: "SP" },
  "15": { city: "Sorocaba", state: "SP" },
  "16": { city: "Ribeirao Preto", state: "SP" },
  "17": { city: "Sao Jose do Rio Preto", state: "SP" },
  "18": { city: "Presidente Prudente", state: "SP" },
  "19": { city: "Campinas", state: "SP" },
  "21": { city: "Rio de Janeiro", state: "RJ" },
  "22": { city: "Campos dos Goytacazes", state: "RJ" },
  "24": { city: "Volta Redonda", state: "RJ" },
  "27": { city: "Vitoria", state: "ES" },
  "28": { city: "Cachoeiro de Itapemirim", state: "ES" },
  "31": { city: "Belo Horizonte", state: "MG" },
  "32": { city: "Juiz de Fora", state: "MG" },
  "33": { city: "Governador Valadares", state: "MG" },
  "34": { city: "Uberlandia", state: "MG" },
  "35": { city: "Pocos de Caldas", state: "MG" },
  "37": { city: "Divinopolis", state: "MG" },
  "38": { city: "Montes Claros", state: "MG" },
  "41": { city: "Curitiba", state: "PR" },
  "42": { city: "Ponta Grossa", state: "PR" },
  "43": { city: "Londrina", state: "PR" },
  "44": { city: "Maringa", state: "PR" },
  "45": { city: "Foz do Iguacu", state: "PR" },
  "46": { city: "Pato Branco", state: "PR" },
  "47": { city: "Joinville", state: "SC" },
  "48": { city: "Florianopolis", state: "SC" },
  "49": { city: "Chapeco", state: "SC" },
  "51": { city: "Porto Alegre", state: "RS" },
  "53": { city: "Pelotas", state: "RS" },
  "54": { city: "Caxias do Sul", state: "RS" },
  "55": { city: "Santa Maria", state: "RS" },
  "61": { city: "Brasilia", state: "DF" },
  "62": { city: "Goiania", state: "GO" },
  "63": { city: "Palmas", state: "TO" },
  "64": { city: "Rio Verde", state: "GO" },
  "65": { city: "Cuiaba", state: "MT" },
  "66": { city: "Rondonopolis", state: "MT" },
  "67": { city: "Campo Grande", state: "MS" },
  "68": { city: "Rio Branco", state: "AC" },
  "69": { city: "Porto Velho", state: "RO" },
  "71": { city: "Salvador", state: "BA" },
  "73": { city: "Ilheus", state: "BA" },
  "74": { city: "Juazeiro", state: "BA" },
  "75": { city: "Feira de Santana", state: "BA" },
  "77": { city: "Vitoria da Conquista", state: "BA" },
  "79": { city: "Aracaju", state: "SE" },
  "81": { city: "Recife", state: "PE" },
  "82": { city: "Maceio", state: "AL" },
  "83": { city: "Joao Pessoa", state: "PB" },
  "84": { city: "Natal", state: "RN" },
  "85": { city: "Fortaleza", state: "CE" },
  "86": { city: "Teresina", state: "PI" },
  "87": { city: "Petrolina", state: "PE" },
  "88": { city: "Juazeiro do Norte", state: "CE" },
  "89": { city: "Picos", state: "PI" },
  "91": { city: "Belem", state: "PA" },
  "92": { city: "Manaus", state: "AM" },
  "93": { city: "Santarem", state: "PA" },
  "94": { city: "Maraba", state: "PA" },
  "95": { city: "Boa Vista", state: "RR" },
  "96": { city: "Macapa", state: "AP" },
  "97": { city: "Coari", state: "AM" },
  "98": { city: "Sao Luis", state: "MA" },
  "99": { city: "Imperatriz", state: "MA" },
};
